var notes = {
  "one":{
    "p1": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer non molestie tellus. Curabitur a tristique orci. Sed euismod sed nulla eget tincidunt. Morbi vitae pellentesque velit. Proin quis aliquet nibh, sed consequat velit. Nam aliquet viverra urna, sit amet vehicula risus eleifend vel. Nam libero tortor, scelerisque vitae libero non, vestibulum elementum tortor. Mauris quis turpis fringilla tortor scelerisque lobortis. Mauris fermentum odio sed interdum tempor. Maecenas imperdiet varius leo quis fringilla. Sed fermentum efficitur mauris, ac porttitor erat varius nec. Cras nisi urna, malesuada vel orci eget, efficitur vestibulum tortor. Nam quis gravida leo. Proin placerat laoreet erat imperdiet lacinia. Aenean luctus dui mauris, non venenatis sem tincidunt eget."},
  
  "two":{ 
    "p1": "Curabitur et pulvinar mi, non convallis felis. Morbi consectetur sed mauris non sagittis. Nullam lobortis sed ligula ut dignissim. Cras bibendum, ante at molestie pellentesque, arcu purus sollicitudin justo, eget cursus lorem justo at neque. Vivamus magna risus, commodo quis mollis at, egestas ut justo. Sed lobortis enim nisl, id ultrices tortor laoreet ut. Sed laoreet viverra euismod. Nunc faucibus sem quis blandit pellentesque. Phasellus sed nisl eget dui accumsan fermentum.",
    "p2": "Nulla quis aliquam dui. Ut ut viverra dolor, at euismod nisl. Nulla tincidunt auctor mollis. Quisque eu feugiat augue. Vivamus a accumsan eros, a iaculis velit. Sed malesuada arcu ipsum, nec ultricies purus finibus a. Proin consequat orci non libero iaculis, quis egestas nunc euismod. Integer pretium laoreet tellus vel blandit. Etiam a mauris id leo auctor ultricies. Donec consequat quis arcu sed rhoncus. Etiam ultrices dui a fringilla pretium. Aliquam erat volutpat."},
  
  "three":{ 
    "p1": "Sed venenatis fringilla dui et tempus. Nam volutpat quis urna ut tempus. Nulla urna justo, sagittis vitae tempor feugiat, laoreet vitae velit. Nulla at justo ornare, lacinia lorem vitae, sagittis ligula. Morbi eget ante vitae erat aliquam aliquam vitae nec tellus. Sed ullamcorper semper purus, et luctus nibh tempus vitae. Sed tempus velit id urna vehicula ultricies. Quisque ornare odio id felis rhoncus, vitae vehicula eros volutpat. Nam aliquet efficitur nibh vitae ullamcorper. Pellentesque laoreet tortor aliquet odio viverra dignissim. Aenean ac lacus et ipsum consequat semper. Nulla pharetra quis erat sit amet faucibus. Cras posuere dolor quis turpis luctus, vitae condimentum sem tincidunt. Vestibulum efficitur lacus a orci ornare eleifend.",
    "p2": "Suspendisse potenti. Quisque a magna arcu. Donec feugiat porttitor lorem, quis gravida tellus molestie id. Aliquam mattis ultricies massa, ut tincidunt neque rhoncus et. Duis et magna a tellus aliquam tempus. Integer efficitur fermentum leo euismod sollicitudin. Quisque sit amet egestas dolor, quis tristique tellus. Vestibulum dignissim dignissim purus quis tincidunt. Fusce turpis mi, feugiat vitae convallis a, mattis vel massa. Suspendisse auctor ac est sed scelerisque. Phasellus tempus, neque eu tristique condimentum, quam magna varius diam, ac efficitur neque magna vitae risus. Aenean vestibulum eu dolor in vulputate. Integer rutrum mollis tellus non tincidunt."},

};
